kind: live
title: barc

defaults:
  life_span: 5d

images:
  barc:
    ref: image:$[[ project.id ]]:v1
    dockerfile: $[[ flow.workspace ]]/Dockerfile
    context: $[[ flow.workspace ]]/
  

volumes:
  hf_cache:
    remote: storage:$[[ flow.project_id ]]/hf_cache
    mount: /root/.cache/huggingface
    local: hf_cache
  data:
    remote: storage:$[[ flow.project_id ]]/data
    mount: /app/data
    local: data
  output:
    remote: storage:$[[ flow.project_id ]]/output
    mount: /app/saves
    local: output

jobs:
  barc_train_induction:
    image: ${{ images.barc.ref }}
    name: barc-train-induction
    preset: H100x4
    detach: true
    env:
      HF_TOKEN: secret:HF_TOKEN
      WANDB_API_KEY: secret:WANDB_API_KEY
      CUDA_VISIBLE_DEVICES: 0,1,2,3
    volumes:
      - ${{ upload(volumes.data).ref_rw }}
      - ${{ volumes.output.ref_rw }}
      - ${{ volumes.hf_cache.ref_rw }}
    # This job runs the supervised fine-tuning script for induction.
    bash: |
      export WANDB_DOCKER=1 &&
      wandb login $WANDB_API_KEY --relogin &&
      echo 'Starting induction training...' &&
      cd /app/finetune/alignment-handbook &&
      ACCELERATE_LOG_LEVEL=info accelerate launch --config_file recipes/accelerate_configs/deepspeed_zero3.yaml --num_processes=4 scripts/run_sft.py recipes/barc/config_fft_llama3_induction_all_data_mixed.yaml --load_in_4bit=false

  barc_train_transduction:
    image: ${{ images.barc.ref }}
    name: barc-train-transduction
    preset: dgx
    detach: true
    env:
      HF_TOKEN: secret:HF_TOKEN
      WANDB_API_KEY: secret:WANDB_API_KEY
      CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    volumes:
      - ${{ upload(volumes.data).ref_rw }}
      - ${{ volumes.output.ref_rw }}
      - ${{ volumes.hf_cache.ref_rw }}
    # This job runs the supervised fine-tuning script for transduction.
    cmd: bash -c "
      export WANDB_DOCKER=1 &&
      wandb login $WANDB_API_KEY --relogin &&
      echo 'Starting induction training...' &&
      cd /app/finetune/alignment-handbook &&
      ACCELERATE_LOG_LEVEL=info accelerate launch --config_file recipes/accelerate_configs/deepspeed_zero3.yaml --num_processes=8 scripts/run_sft.py recipes/barc/transduction_config_fft_engineer_heavy_model.yaml --load_in_4bit=false"

  barc_inference_induction:
    image: ${{ images.barc.ref }}
    name: barc-inference-induction
    preset: H100x1
    detach: true
    env:
      HF_TOKEN: secret:HF_TOKEN
      WANDB_API_KEY: secret:WANDB_API_KEY
      CUDA_VISIBLE_DEVICES: 0
    volumes:
      - ${{ upload(volumes.data).ref_rw }}
      - ${{ volumes.output.ref_rw }}
      - ${{ volumes.hf_cache.ref_rw }}
    cmd: bash -c "
      wandb login $WANDB_API_KEY --relogin &&
      echo 'Starting induction inference...' &&
      pip install vllm==0.6.0 &&
      cd /app &&
      python finetune/inference/vllm_inference.py"

  barc_eval_induction:
    image: ${{ images.barc.ref }}
    name: barc-eval-induction
    preset: cpu-large
    detach: true
    env:
      HF_TOKEN: secret:HF_TOKEN
      WANDB_API_KEY: secret:WANDB_API_KEY
    volumes:
      - ${{ upload(volumes.data).ref_rw }}
      - ${{ volumes.output.ref_rw }}
      - ${{ volumes.hf_cache.ref_rw }}
    cmd: bash -c "
      echo 'Evaluating induction code solutions...' &&
      cd /app &&
      python eval_code_samples.py --answer_file ./finetune/alignment-handbook/arc_problems_validation_400_extra_newline_v2_l3.1-8b-inst-fft-induction-barc-heavy-200k-old-200k-lr1e-5-ep3_temp_0.8_0319133621337110.jsonl"


  barc_inference_transduction:
    image: ${{ images.barc.ref }}
    name: barc-inference-transduction
    preset: H100x1
    detach: true
    env:
      HF_TOKEN: secret:HF_TOKEN
      WANDB_API_KEY: secret:WANDB_API_KEY
    volumes:
      - ${{ upload(volumes.data).ref_rw }}
      - ${{ volumes.output.ref_rw }}
      - ${{ volumes.hf_cache.ref_rw }}
    cmd: bash -c "
      wandb login $WANDB_API_KEY --relogin &&
      echo 'Starting transduction inference...' &&
      pip install vllm==0.5.4 &&
      cd /app/finetune/inference &&
      python vllm_inference_transduction_evaluation.py" 

  barc_eval_ensembled:
    image: ${{ images.barc.ref }}
    name: barc-eval-ensembled
    preset: cpu-large
    detach: true
    env:
      HF_TOKEN: secret:HF_TOKEN
      WANDB_API_KEY: secret:WANDB_API_KEY
    volumes:
      - ${{ upload(volumes.data).ref_rw }}
      - ${{ volumes.output.ref_rw }}
      - ${{ volumes.hf_cache.ref_rw }}
    cmd: bash -c "
      echo 'Evaluating transduction outputs...' &&
      cd /app &&
      python evaluation.py" 

  barc_jupyter_lab:
    image: ${{ images.barc.ref }}
    name: barc-jupyter-lab
    preset: cpu-large
    detach: true
    env:
      HF_TOKEN: secret:HF_TOKEN
      WANDB_API_KEY: secret:WANDB_API_KEY
    volumes:
      - ${{ upload(volumes.data).ref_rw }}
      - ${{ volumes.output.ref_rw }}
      - ${{ volumes.hf_cache.ref_rw }}
    ports:
      - 8888:8888
    cmd: bash -c "
      pip install jupyterlab==4.0.2 &&
      echo 'Starting Jupyter Lab...' &&
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''"